### ISSUE TITLE
Delegate Connectivity Problem

### ISSUE THREAD

**Issue by designermonkey** [harness/harness-cd-community#43]
I'm not sure the best place to log this, please forgive me if this isn't it...

I have placed Harness behind a Traefik edge router which proxies to the nginx container from the provided compose file. Everything so far is working as expected apart from then I add a docker delegate.

I get the following error in the delegate container logs:

```
2022-01-28 11:06:41,317 [1.0.72713-000] 101 [heartbeat-0] INFO  io.harness.watcher.service.WatcherServiceImpl - Current performance [heap-max=179306496, non-heap-max=-1, heap-committed=179306496, non-heap-init=2555904, heap-init=65011712, non-heap-committed=31916032, heap-used=98171312, non-heap-used=30981560] 
2022-01-28 11:06:41,410 [1.0.72713-000] 101 [watcher-0] INFO  io.harness.watcher.service.WatcherServiceImpl - Watching delegate processes: []  
2022-01-28 11:06:41,417 [1.0.72713-000] 101 [watcher-0] WARN  io.harness.watcher.service.WatcherServiceImpl - Unable to fetch delegate version information  
java.net.ConnectException: Failed to connect to my.custom.domain.net/127.0.0.1:80
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:222)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at io.harness.network.Http.getResponseFromUrl(Http.java:600)
	at io.harness.network.Http.getResponseStringFromUrl(Http.java:588)
	at io.harness.watcher.service.WatcherServiceImpl.findExpectedDelegateVersions(WatcherServiceImpl.java:967)
	at io.harness.watcher.service.WatcherServiceImpl.watchDelegate(WatcherServiceImpl.java:546)
	at io.harness.watcher.service.WatcherServiceImpl.syncWatchDelegate(WatcherServiceImpl.java:498)
	at io.harness.threading.Schedulable.run(Schedulable.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
	... 30 common frames omitted
```

I _think_ that the issue is related to the traefik service redirecting the traffic, but I can't be sure. All the uris in the delegate compose conf are specified as the https uri I am using, which is routed to port 80 on the manager container.

Has anyone experienced this or has any helpful ideas?

**Comment by sean-harness** [comment]
Hi @designermonkey, thank you for reaching out for support.

It seems that the docker container is resolving your hostname `my.custom.domain.net` to localhost (or `127.0.0.1`) so it is trying to connect to port 80 within the container.

Do you have a DNS mapping for `my.custom.domain.net` in your `/etc/hosts` file on the host machine?

**Comment by designermonkey** [comment]
Hi @sean-harness thanks for getting back to me.

I have just found the issue while I was compiling some more info for the ticket. I neglected the https on one of the storage URIs.

Isn't rubber ducking useful ;)

Thanks so much. I have another problem but I will see if I can figure it out first.

**Comment by designermonkey** [comment]
I spoke too soon. It's the same error but now with port 443.

I have got the domain in my host's `/etc/hosts` file as the rest of harness is working, just specifically not this container.

```
- MANAGER_HOST_AND_PORT=https://my.custom.domain.net
- WATCHER_STORAGE_URL=https://my.custom.domain.net/storage/wingswatchers
- REMOTE_WATCHER_URL_CDN=https://qa.harness.io/public/shared/watchers/builds
- DELEGATE_STORAGE_URL=https://my.custom.domain.net/storage/wingsdelegates
```

It's something to do with one or more of these env vars. Can I ask, are these defined so that *this* service can talk to thos endpoints, or are they defined for external network access? Would it be feasible to use docker's internal container names instead?

**Comment by sean-harness** [comment]
The rest of Harness is deploy into a docker network so all those containers can talk using their internal names therefore they will not be impacted by the DNS entry on your host machine.

The environment variables within the delegate docker-compose file are there to tell the delegate how to reach the Harness application.

There is likely two ways to solve your issue here.
1. If you have `my.custom.domain.net` mapped to `127.0.0.1` in your `/etc/hosts` file, removing this entry or updating it to point to the real IP address of the Traefik edge router should solve the issue.
1. As you suggested, if you are deploying the delegate onto the same machine as the rest of the Harness application you can indeed use the internal names. Infact this is the default configuration if you do not set the `HARNESS_HOST` variable. To do this replace `my.custom.domain.net` with `host.docker.internal` in the delegate docker-compose.yml file.

**Comment by designermonkey** [comment]
Thanks @sean-harness I'll give those a go.

**Comment by sean-harness** [comment]
No problem, please let us know if you experience any issues.

**Comment by mrsantons** [comment]
Hey @designermonkey I will close this issue. 

If you need any other assistance feel free to open another issue or post in the #cd-community channel in our [slack community](https://join.slack.com/t/harnesscommunity/shared_invite/zt-y4hdqh7p-RVuEQyIl5Hcx4Ck8VCvzBw) or in our [discourse forum](https://community.harness.io/).

Thanks for helping us work out some quirks we need to document so installation can be as easy as possible! 
🚀
