### ISSUE TITLE
Harness doesn't start through the Helm chart

### ISSUE THREAD

**Issue by raelix** [harness/harness-cd-community#50]
Hello everyone,
I'm trying to install Harness through the helm chart but I'm not able to have it working. 
The pipeline-service has multiple errors like:
```java
2022-05-22 17:43:01,209 [main] WARN  io.harness.migration.service.impl.NGMigrationServiceImpl - [Migration] - Pipelines : Failed to run migration CreateTimescaleCDCTablesWhereNotExist because of [Migration]: Migration class io.harness.pms.migration.CreateTimescaleCDCTablesWhereNotExist failed - TIMESCALEDBSERVICE NOT AVAILABLE  
2022-05-22 17:43:14,940 [TemplateRegistrationService-0] ERROR io.harness.remote.client.NGRestUtils - IO error while connecting to the service: /notifications/api/templates/insertOrUpdate  
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.harness.remote.client.AbstractHttpClientFactory.lambda$getUnsafeOkHttpClient$0(AbstractHttpClientFactory.java:135)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.harness.request.RequestContextFilter.lambda$getRequestContextInterceptor$0(RequestContextFilter.java:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.harness.remote.client.AbstractHttpClientFactory.lambda$getGitContextInterceptor$1(AbstractHttpClientFactory.java:165)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.harness.ng.core.CorrelationContext.lambda$getCorrelationIdInterceptor$0(CorrelationContext.java:50)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.harness.remote.client.AbstractHttpClientFactory.lambda$getAuthorizationInterceptor$2(AbstractHttpClientFactory.java:190)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at io.harness.remote.client.NGRestUtils.getResponse(NGRestUtils.java:79)
	at io.harness.remote.client.NGRestUtils.getResponse(NGRestUtils.java:40)
	at io.harness.notification.notificationclient.NotificationClientImpl.saveNotificationTemplate(NotificationClientImpl.java:79)
	at io.harness.NotificationTemplateRegistrar.run(NotificationTemplateRegistrar.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Do you know what I'm doing wrong?

**Comment by mrsantons** [comment]
Hey @raelix let me look into

**Comment by raelix** [comment]
thanks @mrsantons for the quick reply, just to add more details, I'm using k3s on a bare-metal and I set the ```harness_host``` to my host IP but the ```listen_port``` it's not clear to me, looks like the proxy svc use the nodePort but without the ability of setting a fixed port it can be pre-defined in the values.yaml. Can I just use ```harness_host``` to "proxy" and ```listen_port``` to 80?

**Comment by naidu-harness** [comment]
@raelix Thanks for trying harness. Greatly appreciate it.

I just need to understand more about the exact issue you are facing. 

- Are all service pods up & running?
- were you able to open UI with the given Url mentioned in Readme?

**Comment by raelix** [comment]
Hi @naidu-harness , unfortunately the UI doesn't start. To summarize
- The proxy doesn't start waiting ```ng-manager```
- The ```ng-manager``` doesn't start waiting for the ```pipeline-service```
- The ```pipeline-service``` crash due to the previous mentioned issue

Thanks in advance

**Comment by naidu-harness** [comment]
Thanks for the details @raelix .
Would you mind sharing the complete pipeline service logs in a gist or file?

**Comment by raelix** [comment]
Yes, of course, here it's the link:

**Comment by mrsantons** [comment]
Hey @raelix would you be available to hop on a zoom call today so I can capture what is going on?

**Comment by raelix** [comment]
Thanks @mrsantons i really appreciate your availability, could be a good time at 7.30 PM CEST ?

**Comment by mrsantons** [comment]
Yes Could I have your email to send the invite? Or you can send me an invite at marie.antons@harness.io

**Comment by raelix** [comment]
Sure, raelix@hotmail.it, thanks in advance

**Comment by mrsantons** [comment]
Just sent the invite @raelix  -- I look forward to helping you resolve this issue.

**Comment by raelix** [comment]
hello @mrsantons , just to confirm, is our meeting schedule in 15 mins?

**Comment by Abs0luteMatt** [comment]
Hi everyone, did anything come from the zoom call? I have the same issue running from helm.

**Comment by raelix** [comment]
Hi @Abs0luteMatt  we had the meeting yesterday, We found the issues and the fix should be committed to the main branch. To workaround the issue, you have to remove the initContainer from the proxy manifest.

**Comment by Abs0luteMatt** [comment]
Awesome thanks @raelix & @mrsantons, that initContainer removal workaround fixed for me too and I can now start. I will grab the main branch again in due course.

**Comment by Ompragash** [comment]
Thanks for reporting @raelix 
Closing this for now! Feel free to reopen if you run into this issue again.
