### ISSUE TITLE
Harness docker delegate Error

### ISSUE THREAD

**Issue by Jayakumar6** [harness/harness-cd-community#83]
INFO  io.harness.delegate.task.citasks.vm.helper.HttpHelper - [Retrying failed to cleanup stage; attempt: 6 [accountId=I8IrCrK5SfmCOK1a26PpAw, taskId=kh298vjrRRmpRY7FC6soJw-DEL] 
java.net.ConnectException: Failed to connect to /127.0.0.1:3000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at io.harness.delegate.task.citasks.vm.helper.HttpHelper.cleanupStage(HttpHelper.java:88)
	at io.harness.delegate.task.citasks.vm.helper.HttpHelper.lambda$cleanupStageWithRetries$2(HttpHelper.java:84)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:284)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:63)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:70)
	at io.harness.delegate.task.citasks.vm.helper.HttpHelper.cleanupStageWithRetries(HttpHelper.java:84)
	at io.harness.delegate.task.citasks.vm.CIVmCleanupTaskHandler.callRunnerForCleanup(CIVmCleanupTaskHandler.java:46)
	at io.harness.delegate.task.citasks.vm.CIVmCleanupTaskHandler.executeTaskInternal(CIVmCleanupTaskHandler.java:39)
	at io.harness.delegate.task.citasks.vm.CIVmCleanupTaskHandler.executeTaskInternal(CIVmCleanupTaskHandler.java:25)
	at io.harness.delegate.task.citasks.CICleanupTask.run(CICleanupTask.java:52)
	at io.harness.delegate.task.common.AbstractDelegateRunnableTask.runDelegateTask(AbstractDelegateRunnableTask.java:126)
	at io.harness.delegate.task.common.AbstractDelegateRunnableTask.run(AbstractDelegateRunnableTask.java:95)
	at io.prometheus.client.Gauge$Child.setToTime(Gauge.java:207)
	at io.harness.metrics.HarnessMetricRegistry.recordGaugeDuration(HarnessMetricRegistry.java:193)
	at io.harness.delegate.service.DelegateAgentServiceImpl.executeTask(DelegateAgentServiceImpl.java:2192)
	at io.harness.delegate.service.DelegateAgentServiceImpl.lambda$getPostValidationFunction$30(DelegateAgentServiceImpl.java:2133)
	at software.wings.delegatetasks.validation.core.AbstractDelegateValidateTask.validationResults(AbstractDelegateValidateTask.java:73)
	at io.harness.delegate.service.DelegateAgentServiceImpl.dispatchDelegateTask(DelegateAgentServiceImpl.java:2086)
	at io.harness.delegate.service.DelegateAgentServiceImpl.lambda$dispatchDelegateTaskAsync$29(DelegateAgentServiceImpl.java:2008)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 42 common frames omitted

I am running a docker delegate in my local machine to connect with SaaS, delegate is added but the pipeline is failing because of this error...

**Comment by ravilach** [comment]
Repo is deprecated. Will close.
